---
title: "Untitled"
author: "Ted Ladas - s2124289"
date: "09/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(readr)
library(dplyr)
library(lubridate)
```

```{r}
# https://en.wikipedia.org/wiki/Generalised_logistic_function
# A: the lower asymptote;
# K: the upper asymptote when C=1;
# B: the growth rate;
# n >0 : affects near which asymptote maximum growth occurs;
# Q: is related to the value Y(0);
# C: typically takes a value of 1;
sigmoid = function(A=0,M=0,K=1,C=1,Q=1,B=1,n=1, x) {
   y <- A + (K-A) / (C + Q*exp(-B*(x-M)))^(1/n) 
   return(y)
}
```

```{r}
# plot(x1, sigmoid(x=x1), type='l', col='blue')
monthly.cor <- read_csv("./data/CoR.csv")
monthly.cor <- monthly.cor %>% mutate(
  date=strptime(as.character(date), "%d/%m/%Y"),
  date=format(date, "%Y-%m-%d"),
  date=as.Date(date),
  id.col=paste0(month(date),year(date)))

daily.data <- data.frame(date=seq(as.Date("21-01-01"), as.Date("22-12-31"), by="days"))
daily.data <- daily.data %>% mutate(
  id.col=paste0(month(date),year(date))) %>% 
  left_join(monthly.cor) %>%
  fill(CoR) %>%
  rename(
    monthly.CoR = CoR
    ) %>% 
  select(-id.col) %>% 
  mutate(
    days.of.month = days_in_month(date),
    daily.CoR = monthly.CoR/days.of.month,
    x=seq(-365,364,1),
    # growth=sigmoid(x=x),
    # daily.active.usr = 15*(1+lag(growth, default = 0)),
    # margin=-(0.5*(daily.active.usr<15))+0.8*(daily.active.usr>15),
    # daily.rev=daily.CoR/(1-margin),
    # daily.gross.rev=daily.rev-daily.CoR
    ) %>%
  select(-x)
daily.data
```

